backend = "glx";
vsync = true;


shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;
shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'i3-frame'",
    "class_g = 'i3bar'",
    "_GTK_FRAME_EXTENTS"
];

# fading and transitions
fading = true;
fade-delta = 10;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];


blur-method = "dual_kawase";
blur-strength = 5;

blur-background = true;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS"
];

# Opacity settings for windows
active-opacity = 0.75;
inactive-opacity = 0.75;
frame-opacity = 0.9;
inactive-opacity-override = true;

# Targeted transparency
opacity-rule = [
    "85:class_g = 'Alacritty'",
    "85:class_g = 'Kitty'",
    "90:class_g = 'Rofi'"
];

# Applied some stuff only for some applications except browsers,discord etc. cus of lag.

# Disable picom on fullscreen windows
unredir-if-possible = true;
unredir-if-possible-exclude = [ ];

# Additional settings for an aesthetic look
use-damage = true;

# Cleaned Animation Ruleset (Conflicts removed)
animation = true;
animation-stiffness = 350;
animation-window-mass = 0.5;
animation-for-open-window = "fade-in, zoom-in";
animation-for-unmap-window = "fade-out, zoom-out";
animation-for-transient-window = "slide-up";

# Additional settings for aesthetics
corner-radius = 20;
round-borders = 12;
round-borders-exclude = [ ];
